### PR TITLE
Fixed Habitation on Karibou Crew Cab

### PR DESCRIPTION
**Pull request by voicey99**
Made USI-LS config for the KCC functional again as a habitation module.

### CODE REVIEW

**Comment by Esendis** [comment]
Habitation works again with your config but as long as you don't deploy the module. As soon as you deploy the module, it only works in deployed mode.

**Comment by voicey99** [comment]
The Karibou modules are glitchy as it is, and now this? Not sure about how to work around that.

**Comment by Esendis** [comment]
Log issue?

**Comment by BobPalmer** [comment]
huh...  I think you folks just gave me the info I need to sort this.

**Comment by voicey99** [comment]
Yay, we were useful! Anything specific that would make it easier?

**Comment by BobPalmer** [comment]
Yep - I bet the deploy issue occurs based on whether or not the module is crewed ;)

**Comment by voicey99** [comment]
Gave it a test, it does this whether the module is crewed or not.
Also, has the leg deploy bug on these modules been fixed yet? Might it be related?

**Comment by Esendis** [comment]
That bug has been resolved.(Can't remember version)

**Comment by voicey99** [comment]
Last I heard the original bug with the cab legs has been inverted so the cab legs are fine but all the others are glitchy. It was still a thing as of 0.52.2, and there's only been one release since then.

**Comment by Esendis** [comment]
Any way to make habitation permanent till this is sorted?Meaning without an on/off toggle? Tried "isAlwaysActive = True" on the habitation module but no luck.

**Pull request merged**
