### PR TITLE
Added a filter on FuelCell*

### PR DESCRIPTION
**Pull request by alex-dev**
MM seems to throw errors on version 3.1.1, so here it is fixed.

### CODE REVIEW

**Comment by alex-dev** [comment]
Not fixing the bug... Let me investigate deeper.

**Comment by alex-dev** [comment]
Now it is fixed.

**Comment by alex-dev** [comment]
Still not working

**Comment by alex-dev** [comment]
I may have found root cause. Nertea's CryoTanks add a ModuleResourceConverter which breaks stuff... Infact, as it was, any mod adding any module to a Fuel Cell before :AFTER[Squad] would cause the bug to occurs.
MM changed quite a few verification in the last few releases... Among them, variable search may have been updated to throw more errors.

I'll reopen the pull request if I'm right and the bug is properly fixed.

**Comment by BobPalmer** [comment]
Thanks for the tweaks!

**Pull request merged**
